### ISSUE TITLE
Fix `/add relnote` from `mingw-w64-gnutls: update to version <...>` PRs

### ISSUE THREAD

**Issue by dscho** [git-for-windows/gfw-helper-github-app#51]
In https://github.com/git-for-windows/MINGW-packages/pull/98#issuecomment-1826164393, I tried to add a release note but it failed with "Could not determine URL from issue 98".

<details><summary>Full web request</summary>

```yaml
 Headers

Request method: POST
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/3f0c934
X-GitHub-Delivery: 729febe0-8b28-11ee-8786-1f5db08b3774
X-GitHub-Event: issue_comment
X-GitHub-Hook-ID: 392499201
X-GitHub-Hook-Installation-Target-ID: 246505
X-GitHub-Hook-Installation-Target-Type: integration
X-Hub-Signature: sha1=bca4253ffebb9f136cde117b7708884550a6143f
X-Hub-Signature-256: sha256=1187884ec1e78664e6dee109ed4007d8b25309d0dc833bf795f6f10ec76e966a

Payload

{
  "action": "created",
  "issue": {
    "url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/98",
    "repository_url": "https://api.github.com/repos/git-for-windows/MINGW-packages",
    "labels_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/98/labels{/name}",
    "comments_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/98/comments",
    "events_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/98/events",
    "html_url": "https://github.com/git-for-windows/MINGW-packages/pull/98",
    "id": 2007637770,
    "node_id": "PR_kwDOAdUltc5gMxG_",
    "number": 98,
    "title": "mingw-w64-gnutls: update to 3.8.2",
    "user": {
      "login": "gitforwindowshelper[bot]",
      "id": 115591365,
      "node_id": "BOT_kgDOBuPIxQ",
      "avatar_url": "https://avatars.githubusercontent.com/in/246505?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D",
      "html_url": "https://github.com/apps/gitforwindowshelper",
      "followers_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gitforwindowshelper%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 2,
    "created_at": "2023-11-23T07:41:48Z",
    "updated_at": "2023-11-25T00:20:33Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/git-for-windows/MINGW-packages/pulls/98",
      "html_url": "https://github.com/git-for-windows/MINGW-packages/pull/98",
      "diff_url": "https://github.com/git-for-windows/MINGW-packages/pull/98.diff",
      "patch_url": "https://github.com/git-for-windows/MINGW-packages/pull/98.patch",
      "merged_at": null
    },
    "body": "This closes https://github.com/git-for-windows/git/issues/4696",
    "reactions": {
      "url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/98/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/98/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  "comment": {
    "url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/comments/1826164393",
    "html_url": "https://github.com/git-for-windows/MINGW-packages/pull/98#issuecomment-1826164393",
    "issue_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/98",
    "id": 1826164393,
    "node_id": "IC_kwDOAdUltc5s2Q6p",
    "user": {
      "login": "dscho",
      "id": 127790,
      "node_id": "MDQ6VXNlcjEyNzc5MA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/127790?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dscho",
      "html_url": "https://github.com/dscho",
      "followers_url": "https://api.github.com/users/dscho/followers",
      "following_url": "https://api.github.com/users/dscho/following{/other_user}",
      "gists_url": "https://api.github.com/users/dscho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dscho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dscho/subscriptions",
      "organizations_url": "https://api.github.com/users/dscho/orgs",
      "repos_url": "https://api.github.com/users/dscho/repos",
      "events_url": "https://api.github.com/users/dscho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dscho/received_events",
      "type": "User",
      "site_admin": true
    },
    "created_at": "2023-11-25T00:20:32Z",
    "updated_at": "2023-11-25T00:20:32Z",
    "author_association": "MEMBER",
    "body": "/add relnote",
    "reactions": {
      "url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/comments/1826164393/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  "repository": {
    "id": 30746037,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMDc0NjAzNw==",
    "name": "MINGW-packages",
    "full_name": "git-for-windows/MINGW-packages",
    "private": false,
    "owner": {
      "login": "git-for-windows",
      "id": 4571183,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1NzExODM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4571183?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/git-for-windows",
      "html_url": "https://github.com/git-for-windows",
      "followers_url": "https://api.github.com/users/git-for-windows/followers",
      "following_url": "https://api.github.com/users/git-for-windows/following{/other_user}",
      "gists_url": "https://api.github.com/users/git-for-windows/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/git-for-windows/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/git-for-windows/subscriptions",
      "organizations_url": "https://api.github.com/users/git-for-windows/orgs",
      "repos_url": "https://api.github.com/users/git-for-windows/repos",
      "events_url": "https://api.github.com/users/git-for-windows/events{/privacy}",
      "received_events_url": "https://api.github.com/users/git-for-windows/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/git-for-windows/MINGW-packages",
    "description": "Package scripts for MinGW-w64 targets to build under MSYS2.",
    "fork": true,
    "url": "https://api.github.com/repos/git-for-windows/MINGW-packages",
    "forks_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/forks",
    "keys_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/teams",
    "hooks_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/hooks",
    "issue_events_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/events{/number}",
    "events_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/events",
    "assignees_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/assignees{/user}",
    "branches_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/branches{/branch}",
    "tags_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/tags",
    "blobs_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/languages",
    "stargazers_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/stargazers",
    "contributors_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/contributors",
    "subscribers_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/subscribers",
    "subscription_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/subscription",
    "commits_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/contents/{+path}",
    "compare_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/merges",
    "archive_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/downloads",
    "issues_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/issues{/number}",
    "pulls_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/labels{/name}",
    "releases_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/releases{/id}",
    "deployments_url": "https://api.github.com/repos/git-for-windows/MINGW-packages/deployments",
    "created_at": "2015-02-13T07:48:21Z",
    "updated_at": "2023-09-06T08:42:20Z",
    "pushed_at": "2023-11-24T06:47:07Z",
    "git_url": "git://github.com/git-for-windows/MINGW-packages.git",
    "ssh_url": "git@github.com:git-for-windows/MINGW-packages.git",
    "clone_url": "https://github.com/git-for-windows/MINGW-packages.git",
    "svn_url": "https://github.com/git-for-windows/MINGW-packages",
    "homepage": null,
    "size": 26881,
    "stargazers_count": 37,
    "watchers_count": 37,
    "language": "Shell",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 54,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": {
      "key": "bsd-3-clause",
      "name": "BSD 3-Clause \"New\" or \"Revised\" License",
      "spdx_id": "BSD-3-Clause",
      "url": "https://api.github.com/licenses/bsd-3-clause",
      "node_id": "MDc6TGljZW5zZTU="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 54,
    "open_issues": 2,
    "watchers": 37,
    "default_branch": "main",
    "custom_properties": {

    }
  },
  "organization": {
    "login": "git-for-windows",
    "id": 4571183,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ1NzExODM=",
    "url": "https://api.github.com/orgs/git-for-windows",
    "repos_url": "https://api.github.com/orgs/git-for-windows/repos",
    "events_url": "https://api.github.com/orgs/git-for-windows/events",
    "hooks_url": "https://api.github.com/orgs/git-for-windows/hooks",
    "issues_url": "https://api.github.com/orgs/git-for-windows/issues",
    "members_url": "https://api.github.com/orgs/git-for-windows/members{/member}",
    "public_members_url": "https://api.github.com/orgs/git-for-windows/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/4571183?v=4",
    "description": ""
  },
  "sender": {
    "login": "dscho",
    "id": 127790,
    "node_id": "MDQ6VXNlcjEyNzc5MA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/127790?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dscho",
    "html_url": "https://github.com/dscho",
    "followers_url": "https://api.github.com/users/dscho/followers",
    "following_url": "https://api.github.com/users/dscho/following{/other_user}",
    "gists_url": "https://api.github.com/users/dscho/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dscho/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dscho/subscriptions",
    "organizations_url": "https://api.github.com/users/dscho/orgs",
    "repos_url": "https://api.github.com/users/dscho/repos",
    "events_url": "https://api.github.com/users/dscho/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dscho/received_events",
    "type": "User",
    "site_admin": true
  },
  "installation": {
    "id": 31544731,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzE1NDQ3MzE="
  }
}

```
</details>

When I tried the same from https://github.com/git-for-windows/MSYS2-packages/pull/134#issuecomment-1826164511, however, [it worked](https://github.com/git-for-windows/build-extra/commit/cea96d33a525a315767f5765fa80a66f95ec76e5).

My guess is that the `mingw-w64-` prefix trips up GitForWindowsHelper.
